# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 03:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(verbose_name='Available from')),
                ('end_date', models.DateTimeField(verbose_name='Available to')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate_Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate_Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Availability')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('chosen_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chosen_activity', to='main.Activity')),
                ('chosen_date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chosen_date', to='main.Availability')),
                ('suggested_activities', models.ManyToManyField(related_name='suggested_activities', to='main.Activity')),
                ('suggested_dates', models.ManyToManyField(related_name='suggested_dates', to='main.Availability')),
            ],
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name='preference',
            name='user',
            field=models.ManyToManyField(to='main.User'),
        ),
        migrations.AddField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(to='main.User'),
        ),
        migrations.AddField(
            model_name='candidate_availability',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Group'),
        ),
        migrations.AddField(
            model_name='candidate_availability',
            name='voters',
            field=models.ManyToManyField(to='main.User'),
        ),
        migrations.AddField(
            model_name='candidate_activity',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Group'),
        ),
        migrations.AddField(
            model_name='candidate_activity',
            name='voters',
            field=models.ManyToManyField(to='main.User'),
        ),
        migrations.AddField(
            model_name='availability',
            name='user',
            field=models.ManyToManyField(to='main.User'),
        ),
        migrations.AddField(
            model_name='activity',
            name='preferences',
            field=models.ManyToManyField(to='main.Preference'),
        ),
    ]
