# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 04:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='user',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='availability',
            field=models.ManyToManyField(to='main.Availability'),
        ),
        migrations.AddField(
            model_name='user',
            name='preference',
            field=models.ManyToManyField(to='main.Preference'),
        ),
        migrations.AlterField(
            model_name='group',
            name='chosen_activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chosen_activity', to='main.Activity'),
        ),
        migrations.AlterField(
            model_name='group',
            name='chosen_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chosen_date', to='main.Availability'),
        ),
        migrations.AlterField(
            model_name='group',
            name='suggested_activities',
            field=models.ManyToManyField(blank=True, null=True, related_name='suggested_activities', to='main.Activity'),
        ),
        migrations.AlterField(
            model_name='group',
            name='suggested_dates',
            field=models.ManyToManyField(blank=True, null=True, related_name='suggested_dates', to='main.Availability'),
        ),
    ]
